// <auto-generated />
using System;
using GPUSpecServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GPUSpecServer.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251026044048_schema")]
    partial class schema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GPUSpecServer.Data.Models.Architecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("Name");

                    b.ToTable("Architectures");
                });

            modelBuilder.Entity("GPUSpecServer.Data.Models.Chip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GenerationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("chip_package")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("cuda_major_version")
                        .HasColumnType("int");

                    b.Property<int?>("cuda_minor_version")
                        .HasColumnType("int");

                    b.Property<int?>("directx_major_version")
                        .HasColumnType("int");

                    b.Property<int?>("directx_minor_version")
                        .HasColumnType("int");

                    b.Property<int?>("opencl_major_version")
                        .HasColumnType("int");

                    b.Property<int?>("opencl_minor_version")
                        .HasColumnType("int");

                    b.Property<int?>("opengl_major_version")
                        .HasColumnType("int");

                    b.Property<int?>("opengl_minor_version")
                        .HasColumnType("int");

                    b.Property<int?>("shader_model_major_version")
                        .HasColumnType("int");

                    b.Property<int?>("shader_model_minor_version")
                        .HasColumnType("int");

                    b.Property<int?>("transistors")
                        .HasColumnType("int");

                    b.Property<int?>("vulkan_major_version")
                        .HasColumnType("int");

                    b.Property<int?>("vulkan_minor_version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId");

                    b.HasIndex("Name");

                    b.ToTable("Chips");
                });

            modelBuilder.Entity("GPUSpecServer.Data.Models.Generation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Generations");
                });

            modelBuilder.Entity("GPUSpecServer.Data.Models.GenerationArchitecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchitectureId")
                        .HasColumnType("int");

                    b.Property<int>("GenerationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArchitectureId");

                    b.HasIndex("GenerationId");

                    b.ToTable("GenerationArchitectures");
                });

            modelBuilder.Entity("GPUSpecServer.Data.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("GPUSpecServer.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("rt_cores")
                        .HasColumnType("int");

                    b.Property<int>("tensor_cores")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("GPUSpecServer.Data.Models.ProductChip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChipId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("base_clock")
                        .HasColumnType("int");

                    b.Property<int?>("board_length")
                        .HasColumnType("int");

                    b.Property<string>("board_slot_width")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("board_width")
                        .HasColumnType("int");

                    b.Property<int>("boost_clock")
                        .HasColumnType("int");

                    b.Property<string>("bus_interface")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("density")
                        .HasColumnType("real");

                    b.Property<int?>("die_size")
                        .HasColumnType("int");

                    b.Property<string>("display_connectors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("foundry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("fp16")
                        .HasColumnType("real");

                    b.Property<float>("fp32")
                        .HasColumnType("real");

                    b.Property<float>("fp64")
                        .HasColumnType("real");

                    b.Property<int>("l1_cache")
                        .HasColumnType("int");

                    b.Property<float>("l2_cache")
                        .HasColumnType("real");

                    b.Property<string>("memory_bandwidth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("memory_bus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("memory_clock")
                        .HasColumnType("int");

                    b.Property<string>("memory_size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("memory_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("pixel_rate")
                        .HasColumnType("real");

                    b.Property<string>("power_connectors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("process_size")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("release_date")
                        .HasColumnType("date");

                    b.Property<int>("rops")
                        .HasColumnType("int");

                    b.Property<string>("shading_units")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("smus")
                        .HasColumnType("int");

                    b.Property<int?>("suggested_psu")
                        .HasColumnType("int");

                    b.Property<int?>("tdp")
                        .HasColumnType("int");

                    b.Property<float>("texture_rate")
                        .HasColumnType("real");

                    b.Property<int>("tmus")
                        .HasColumnType("int");

                    b.Property<string>("tpu_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tpu_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChipId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductChips");
                });

            modelBuilder.Entity("GPUSpecServer.Data.Models.Architecture", b =>
                {
                    b.HasOne("GPUSpecServer.Data.Models.Manufacturer", "Manufacturer")
                        .WithMany("Architectures")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("GPUSpecServer.Data.Models.Chip", b =>
                {
                    b.HasOne("GPUSpecServer.Data.Models.Generation", "Generation")
                        .WithMany("Chips")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("GPUSpecServer.Data.Models.GenerationArchitecture", b =>
                {
                    b.HasOne("GPUSpecServer.Data.Models.Architecture", "Architecture")
                        .WithMany("GenerationArchitectures")
                        .HasForeignKey("ArchitectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPUSpecServer.Data.Models.Generation", "Generation")
                        .WithMany("GenerationArchitectures")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Architecture");

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("GPUSpecServer.Data.Models.ProductChip", b =>
                {
                    b.HasOne("GPUSpecServer.Data.Models.Chip", "Chip")
                        .WithMany("ProductChips")
                        .HasForeignKey("ChipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPUSpecServer.Data.Models.Product", "Product")
                        .WithMany("ProductChips")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chip");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GPUSpecServer.Data.Models.Architecture", b =>
                {
                    b.Navigation("GenerationArchitectures");
                });

            modelBuilder.Entity("GPUSpecServer.Data.Models.Chip", b =>
                {
                    b.Navigation("ProductChips");
                });

            modelBuilder.Entity("GPUSpecServer.Data.Models.Generation", b =>
                {
                    b.Navigation("Chips");

                    b.Navigation("GenerationArchitectures");
                });

            modelBuilder.Entity("GPUSpecServer.Data.Models.Manufacturer", b =>
                {
                    b.Navigation("Architectures");
                });

            modelBuilder.Entity("GPUSpecServer.Data.Models.Product", b =>
                {
                    b.Navigation("ProductChips");
                });
#pragma warning restore 612, 618
        }
    }
}
