// <auto-generated />
using System;
using GPUSpecServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GPUSpecServer.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251027230011_seeding")]
    partial class seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GPUSpecServer.Data.Models.Chip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("chip_package")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("cuda_major_version")
                        .HasColumnType("int");

                    b.Property<int?>("cuda_minor_version")
                        .HasColumnType("int");

                    b.Property<float?>("density")
                        .HasColumnType("real");

                    b.Property<int?>("die_size")
                        .HasColumnType("int");

                    b.Property<int?>("directx_major_version")
                        .HasColumnType("int");

                    b.Property<int?>("directx_minor_version")
                        .HasColumnType("int");

                    b.Property<string>("foundry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("opencl_major_version")
                        .HasColumnType("int");

                    b.Property<int?>("opencl_minor_version")
                        .HasColumnType("int");

                    b.Property<int?>("opengl_major_version")
                        .HasColumnType("int");

                    b.Property<int?>("opengl_minor_version")
                        .HasColumnType("int");

                    b.Property<int?>("process_size")
                        .HasColumnType("int");

                    b.Property<int?>("shader_model_major_version")
                        .HasColumnType("int");

                    b.Property<int?>("shader_model_minor_version")
                        .HasColumnType("int");

                    b.Property<int?>("transistors")
                        .HasColumnType("int");

                    b.Property<int?>("vulkan_major_version")
                        .HasColumnType("int");

                    b.Property<int?>("vulkan_minor_version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Chips");
                });

            modelBuilder.Entity("GPUSpecServer.Data.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChipId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("architecture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("base_clock")
                        .HasColumnType("int");

                    b.Property<int?>("board_length")
                        .HasColumnType("int");

                    b.Property<string>("board_slot_width")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("board_width")
                        .HasColumnType("int");

                    b.Property<int>("boost_clock")
                        .HasColumnType("int");

                    b.Property<string>("bus_interface")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("display_connectors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("fp16")
                        .HasColumnType("real");

                    b.Property<float?>("fp32")
                        .HasColumnType("real");

                    b.Property<float?>("fp64")
                        .HasColumnType("real");

                    b.Property<string>("generation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("l1_cache")
                        .HasColumnType("real");

                    b.Property<float>("l2_cache")
                        .HasColumnType("real");

                    b.Property<string>("manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("memory_bandwidth")
                        .HasColumnType("real");

                    b.Property<int?>("memory_bus")
                        .HasColumnType("int");

                    b.Property<int?>("memory_clock")
                        .HasColumnType("int");

                    b.Property<float>("memory_size")
                        .HasColumnType("real");

                    b.Property<string>("memory_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("pixel_rate")
                        .HasColumnType("real");

                    b.Property<string>("power_connectors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("release_date")
                        .HasColumnType("date");

                    b.Property<int>("rops")
                        .HasColumnType("int");

                    b.Property<string>("shading_units")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("smus")
                        .HasColumnType("int");

                    b.Property<int?>("suggested_psu")
                        .HasColumnType("int");

                    b.Property<int?>("tdp")
                        .HasColumnType("int");

                    b.Property<float>("texture_rate")
                        .HasColumnType("real");

                    b.Property<int>("tmus")
                        .HasColumnType("int");

                    b.Property<string>("tpu_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tpu_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChipId");

                    b.HasIndex("ProductId");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("GPUSpecServer.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("rt_cores")
                        .HasColumnType("int");

                    b.Property<int>("tensor_cores")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("GPUSpecServer.Data.Models.Listing", b =>
                {
                    b.HasOne("GPUSpecServer.Data.Models.Chip", "Chip")
                        .WithMany("Listings")
                        .HasForeignKey("ChipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPUSpecServer.Data.Models.Product", "Product")
                        .WithMany("Listings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chip");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GPUSpecServer.Data.Models.Chip", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("GPUSpecServer.Data.Models.Product", b =>
                {
                    b.Navigation("Listings");
                });
#pragma warning restore 612, 618
        }
    }
}
